name: Deploy to Kubernetes via Argo CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML
        run: yamllint k8s
      - name: Notify
        run: echo "Changes pushed. Argo CD will sync automatically."
